namespace ProductReviews.Domain.Persistence.Seeding;

internal sealed record SeedAuthor(Guid Id, string Name);

internal sealed record SeedReview(
    string Author,
    int Rating,
    string Title,
    string Body,
    string? Pros,
    string? Cons,
    int Helpful,
    int DaysAgo);

internal sealed record SeedProduct(
    long Id,
    string Slug,
    string Name,
    string Description,
    string? ImageUrl,
    SeedReview[] Reviews);

/// <summary>The demo catalog. Authors carry fixed Guids so seeded data is stable
/// across runs; Helpful is the target helpfulness score (negative = downvoted).</summary>
internal static class DemoCatalog
{
    public static readonly IReadOnlyList<SeedAuthor> Authors =
    [
        new(new Guid("00000000-0000-0000-0000-000000000001"), "Alice Novak"),
        new(new Guid("00000000-0000-0000-0000-000000000002"), "Bob Marsh"),
        new(new Guid("00000000-0000-0000-0000-000000000003"), "Carol Jensen"),
        new(new Guid("00000000-0000-0000-0000-000000000004"), "Dave Kim"),
        new(new Guid("00000000-0000-0000-0000-000000000005"), "Eve Horak"),
        new(new Guid("00000000-0000-0000-0000-000000000006"), "Frank Ortega"),
        new(new Guid("00000000-0000-0000-0000-000000000007"), "Grace Liu"),
        new(new Guid("00000000-0000-0000-0000-000000000008"), "Henry Walsh"),
    ];

    public static readonly IReadOnlyList<SeedProduct> Products =
    [
        new(1, "sony-wh-1000xm5", "Sony WH-1000XM5 Wireless Headphones",
            "Industry-leading noise cancelling over-ear headphones with 30-hour battery life, multipoint Bluetooth, and a fold-flat travel case.",
            "https://picsum.photos/seed/sony-wh-1000xm5/600/400",
            [
                new("Alice Novak", 5, "The commute upgrade I didn't know I needed",
                    "The noise cancelling erases the tram entirely. I get off with more energy than I got on, and the battery outlasts a week of commuting.",
                    "Best-in-class noise cancelling", "Touch controls take a week to learn", 7, 45),
                new("Bob Marsh", 4, "Excellent sound, slightly tight fit",
                    "Warm, detailed sound with plenty of bass. After three hours the clamping force starts to bother me, so they lose a star for marathon sessions.",
                    "Rich, warm sound signature", "Clamps a little after long sessions", 5, 38),
                new("Carol Jensen", 5, "Calls finally sound professional",
                    "I bought these for video calls and the microphone array is shockingly good. Colleagues stopped asking if I moved to a quieter flat.",
                    "Crystal-clear call quality", null, 4, 21),
                new("Dave Kim", 4, "Great, but bring the app",
                    "Out of the box the EQ is bass-heavy for my taste. Ten minutes in the companion app fixed it. Hardware is flawless.",
                    null, "Default EQ needs tweaking", 2, 9),
            ]),
        new(2, "usb-c-cable-pack", "USB-C Cable 3-Pack (1m)",
            "Braided 60W USB-C to USB-C cables in one-metre length. E-marker chips, aluminium strain relief, and a lifetime replacement promise.",
            "https://picsum.photos/seed/usb-c-cable-pack/600/400",
            [
                new("Eve Horak", 4, "Cables that survive my backpack",
                    "Six months of being crushed under laptops and books and all three still work. The braiding shows no fraying yet.",
                    "Tough braided jacket", null, 3, 52),
                new("Frank Ortega", 3, "Fine, but only 60W",
                    "They charge my phone perfectly well. Just know they will not fast-charge a 16-inch laptop — that needs a 100W cable, which these are not.",
                    null, "Not for high-wattage laptops", 4, 33),
                new("Grace Liu", 3, "Exactly what the label says",
                    "One metre is shorter than you think when your socket is behind the sofa. Quality is fine; measure before you buy.",
                    null, "One metre is short in practice", 1, 17),
            ]),
        new(3, "acme-smartwatch", "Acme Pro Smartwatch",
            "A budget smartwatch with a bright AMOLED display, heart-rate tracking, sleep insights, and a claimed seven-day battery.",
            "https://picsum.photos/seed/acme-smartwatch/600/400",
            [
                new("Henry Walsh", 2, "Seven-day battery is a fantasy",
                    "With the always-on display and workout tracking I get barely two days. The watch itself is fine; the marketing is not.",
                    "Bright, crisp display", "Real battery life is a third of the claim", 6, 41),
                new("Alice Novak", 1, "Returned after a week",
                    "The heart-rate sensor read 140 while I was sitting still and 90 mid-sprint. For a fitness watch, that's disqualifying.",
                    null, "Wildly inaccurate heart-rate sensor", 5, 29),
                new("Bob Marsh", 3, "Decent notifications, poor fitness",
                    "As a wrist notification mirror it does the job and the screen is lovely. Treat the health metrics as decoration.",
                    "Great screen for the price", "Health metrics are not trustworthy", 2, 15),
                new("Carol Jensen", 1, "Strap broke in a fortnight",
                    "The proprietary strap lug snapped clean off fourteen days in. No standard straps fit, so the watch is now a paperweight.",
                    null, "Proprietary strap, fragile lugs", 3, 8),
            ]),
        new(4, "logi-mx-master-3s", "Logitech MX Master 3S",
            "The flagship productivity mouse: 8K DPI sensor, silent switches, the MagSpeed infinite scroll wheel, and three-device pairing.",
            "https://picsum.photos/seed/logi-mx-master-3s/600/400",
            [
                new("Dave Kim", 5, "The scroll wheel ruins other mice",
                    "Flywheel scrolling through thousand-line files is genuinely addictive. Once you flick through a code review in one spin, everything else feels broken.",
                    "MagSpeed wheel is unmatched", null, 7, 60),
                new("Eve Horak", 5, "Silent clicks saved my marriage",
                    "I work nights next to a sleeping partner. The 3S clicks are near-silent and the shape keeps my wrist happy through ten-hour days.",
                    "Whisper-quiet switches", "Not for small hands", 4, 34),
                new("Frank Ortega", 4, "Heavy, in a good way — mostly",
                    "Rock solid and precise, but at 141 grams you will notice it after a fast-paced day. Desk workers will love it; flick-aimers will not.",
                    null, "Too heavy for quick movements", 3, 19),
                new("Grace Liu", 5, "Three computers, one mouse",
                    "Pairs with my work laptop, home desktop, and tablet, and flows between them like they're one machine. Setup took five minutes.",
                    "Effortless multi-device switching", null, 2, 6),
            ]),
        new(5, "boombox-mini", "BoomBox Mini Bluetooth Speaker",
            "A palm-sized Bluetooth speaker promising 360-degree sound, IPX5 splash resistance, and twelve hours of playback.",
            "https://picsum.photos/seed/boombox-mini/600/400",
            [
                new("Henry Walsh", 1, "Distorts at half volume",
                    "Anything above background-music level and the driver crackles like a broken radio. Twelve-hour battery means little when you can't stand the sound.",
                    null, "Audible distortion above 50% volume", 6, 47),
                new("Alice Novak", 2, "Okay for podcasts, nothing else",
                    "Voice content is passable. Music has no low end at all — the '360-degree sound' is 360 degrees of tin.",
                    "Small enough for any bag", "No bass whatsoever", 4, 26),
                new("Bob Marsh", 2, "Bluetooth drops every few songs",
                    "Random half-second dropouts with the phone two metres away. Firmware update didn't help. Pass.",
                    null, "Unstable Bluetooth connection", 1, 11),
            ]),
        new(6, "ipad-air-11", "iPad Air 11\" (M3, 256GB)",
            "Apple's mid-range 11-inch tablet with the M3 chip, Apple Pencil Pro support, and a 256GB configuration in four colours.",
            "https://picsum.photos/seed/ipad-air-11/600/400",
            [
                new("Carol Jensen", 5, "Replaced my laptop for travel",
                    "With a keyboard folio this handles email, documents, and video editing on the road. The M3 never stutters and the battery lasts a full flight.",
                    "M3 is overkill in the best way", "Accessories cost extra — budget for them", 6, 50),
                new("Dave Kim", 4, "Wonderful screen, 60Hz though",
                    "Colours and brightness are superb for the price. Coming from a 120Hz phone, scrolling looks a touch choppy — you notice it for a day, then forget.",
                    "Gorgeous laminated display", "No ProMotion at this price", 5, 31),
                new("Eve Horak", 5, "The sketching setup I recommend to students",
                    "Pencil Pro hover plus zero perceptible latency makes this the best value drawing tablet that is also, well, a computer.",
                    "Perfect Pencil Pro integration", null, 3, 14),
                new("Frank Ortega", 4, "Storage math finally works",
                    "256GB base storage means I stopped juggling offloaded apps. Would be five stars with Face ID instead of the power-button sensor.",
                    null, "Touch ID placement is awkward", 1, 5),
            ]),
        new(7, "xyz-mechanical-keyboard", "XYZ Mechanical Keyboard (Brown switches)",
            "A hot-swappable 87-key mechanical keyboard with tactile brown switches, PBT keycaps, south-facing RGB, and tri-mode connectivity.",
            "https://picsum.photos/seed/xyz-mechanical-keyboard/600/400",
            [
                new("Grace Liu", 4, "Punches far above its price",
                    "Pre-lubed stabilisers, foam dampening, and PBT caps at this price is absurd. The stock browns are decent; I swapped them anyway because I could.",
                    "Hot-swap sockets, no soldering", null, 5, 42),
                new("Henry Walsh", 4, "Solid board, mushy spacebar",
                    "Alphas feel crisp and the case has zero flex. The spacebar sounds like a wet sock — five minutes of tape fixed it, but I shouldn't have to.",
                    "Rock-solid aluminium plate", "Spacebar needs modding", 3, 27),
                new("Alice Novak", 5, "My first mechanical, no regrets",
                    "Went from a laptop keyboard to this and my typing speed jumped 15 wpm. Battery lasts weeks with the RGB off.",
                    "Weeks of battery over Bluetooth", "RGB software is Windows-only", 2, 12),
                new("Bob Marsh", 3, "Good hardware, beta software",
                    "The keyboard itself deserves four stars. The configuration app crashes, forgets profiles, and once remapped my Q to a media key. Buy it if you never touch the software.",
                    null, "Companion app is unreliable", 4, 7),
            ]),
        new(8, "travelpro-tripod", "TravelPro Phone Tripod",
            "A foldable aluminium phone tripod extending to 1.6m, with a detachable Bluetooth shutter remote and a 360-degree ball head.",
            "https://picsum.photos/seed/travelpro-tripod/600/400",
            [
                new("Carol Jensen", 4, "Lighter than my water bottle",
                    "Folds to the length of a paperback and disappears into a daypack. Perfectly steady indoors; wind is another story.",
                    "Genuinely pocketable", "Wobbles in any breeze", 3, 36),
                new("Dave Kim", 2, "The ball head does not lock",
                    "With a larger phone the head slowly droops mid-timelapse. Every long recording ends pointing at my shoes.",
                    null, "Head sags under heavier phones", 4, 22),
                new("Eve Horak", 3, "Remote is the best part",
                    "The little Bluetooth shutter is worth half the price alone. The legs are fine on flat ground, fiddly on trails.",
                    "Handy detachable remote", "Leg locks are fiddly", 1, 10),
            ]),
        new(9, "single-origin-coffee", "Highland Single-Origin Coffee 1kg",
            "Medium-roast single-origin arabica from high-altitude farms, roasted weekly in small batches with tasting notes of caramel, plum, and cocoa.",
            "https://picsum.photos/seed/single-origin-coffee/600/400",
            [
                new("Frank Ortega", 5, "Roast date on the bag, flavour in the cup",
                    "Arrived four days off roast and the difference from supermarket beans is night and day. The plum note is really there on a V60.",
                    "Always fresh — roast date printed", null, 6, 39),
                new("Grace Liu", 5, "Converted my espresso-hating partner",
                    "Sweet, chocolatey, zero bitterness even when I fumble the shot. Our weekend ritual now starts with this bag.",
                    "Forgiving for beginners", "Sells out fast", 4, 24),
                new("Henry Walsh", 4, "Excellent, mind the grind",
                    "As filter coffee it's superb. For espresso you'll chase the grind setting for a few days — worth it, but budget some beans for dialling in.",
                    null, "Needs careful dialling for espresso", 2, 13),
                new("Alice Novak", 5, "The caramel note is not marketing",
                    "Blind-tested against two other roasters with friends and this won unanimously. Sweet finish that lingers.",
                    "Distinct caramel finish", null, 3, 4),
            ]),
        new(10, "powerjuice-10000", "PowerJuice 10000 Mini Power Bank",
            "A credit-card footprint 10,000mAh power bank with built-in USB-C cable, 20W fast charge, and pass-through charging.",
            "https://picsum.photos/seed/powerjuice-10000/600/400",
            [
                new("Bob Marsh", 2, "Half the promised capacity",
                    "Measured with a USB meter it delivers barely 5,400mAh to my phone. Physics taxes every power bank, but this is beyond the usual conversion loss.",
                    null, "Real capacity far below spec", 5, 44),
                new("Carol Jensen", 3, "Handy until the cable frays",
                    "The built-in cable is genius for three months. Then the strain relief cracks, and unlike a normal bank you can't just swap the cable.",
                    "No cables to forget", "Built-in cable is the weak point", 3, 28),
                new("Dave Kim", 1, "Gets alarmingly hot",
                    "Fast-charging a phone while topping the bank up itself made it too hot to hold. I stopped using it; a charger should not double as a hand warmer.",
                    null, "Overheats during pass-through", 4, 16),
            ]),
    ];
}
